version: '3'

services:

  web:
    image: nginx:1.22
    ports:
      - 9999:80
    depends_on:
      - app
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  app:
    build: ./infra/php
    depends_on:
      - db
    volumes:
      - ./src:/data


  db:
    build: ./infra/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
